src/BitStream/src/main.cpp File Reference
#include <iostream>
#include <fstream>
#include "BitStream.h"
Functions
int main (int argc, char const *argv[])
Function Documentation
main()
int main (int argc, char const * argv[])
Definition at line 7 of file main.cpp.
{
    // criar class bit Stream e abrir ficheiro teste
    BitStream fileBit("files/teste");
    int arr[] = {0,1,0,0,0,1,0,0};
    // escrever um conjuto de bits
    fileBit.writeBits(&arr[0],8);
    //escrever 1 bit
    fileBit.writeBit(1);
    //fechar ficheiro
    fileBit.close();
    //abrir ficheino novamente
    fileBit.open("files/teste");
    // ler um array de bits
    int* out = fileBit.readBits(8);
    for (size_t i = 0; i < 8; i++)
    {
        cout << arr[i];
    }
    cout << "\n";
    //ler um bit
    cout << "bit:" << fileBit.readBit()<< "\n";
    //fechar ficheiro
    fileBit.close();
        
    return 0;
    
}
References BitStream::close(), BitStream::open(), BitStream::readBit(), BitStream::readBits(), BitStream::writeBit(), and BitStream::writeBits().