BitStream Class Reference
A class to read/write bits from/to a file.
#include <BitStream.h>
Public Member Functions
BitStream (string, char)
Bit buffer used for reading from a file.
~BitStream ()
Destructor.
void close ()
Writes any remaining bits and closes the file stream.
void open (string)
Opens a file as a filestream.
bool hasNext ()
Checks if the file stream has bits left to read.
void writeBit (int)
Writes a single bit to the file stream.
void writeBits (int, int)
Writes an array of bits to the file stream.
int readBit ()
Reads a single bit from the file stream.
int readBits (int)
Reads an array of bits from the file stream.
BitStream (string, char)
Bit buffer used for reading from a file.
~BitStream ()
Destructor.
void close ()
Writes any remaining bits and closes the file stream.
void open (string)
Opens a file as a filestream.
bool hasNext ()
Checks if the file stream has bits left to read.
void writeBit (int)
Writes a single bit to the file stream.
void writeBits (int, int)
Writes an array of bits to the file stream.
int readBit ()
Reads a single bit from the file stream.
int readBits (int)
Reads an array of bits from the file stream.
BitStream (string, char)
Constructor.
~BitStream ()
Destructor.
void close ()
Writes any remaining bits and closes the file stream.
bool hasNext ()
Checks if the file stream has bits left to read.
void writeBit (int)
Writes a single bit to the file stream.
void writeBits (int, int)
Writes an array of bits to the file stream.
int readBit ()
Reads a single bit from the file stream.
int readBits (int)
Reads an array of bits from the file stream.
BitStream (string, char)
Constructor.
~BitStream ()
Destructor.
void close ()
Writes any remaining bits and closes the file stream.
bool hasNext ()
Checks if the file stream has bits left to read.
void writeBit (int)
Writes a single bit to the file stream.
void writeBits (int, int)
Writes an array of bits to the file stream.
int readBit ()
Reads a single bit from the file stream.
int readBits (int)
Reads an array of bits from the file stream.
Private Attributes
fstream file
The file stream.
char bitBuffer = 0
Bit buffer used for writing in a file.
unsigned int currentBit = 0
Bit counter used when writing to a file.
Detailed Description
A class to read/write bits from/to a file.
Definition at line 11 of file BitStream.h.
Constructor & Destructor Documentation
BitStream() [1/4]
BitStream::BitStream (string name, char write)
Bit buffer used for reading from a file.
Constructor.
Parameters
name The file path.
mode The mode in witch the BitStream operates 'r' to read, 'w' to write
Definition at line 8 of file BitStream.cpp.
                                          {
    if(write == 'w'){
        file.open(name,ios_base::out);
    }else if(write == 'r'){
        file.open(name,ios_base::in);
    }else{
        throw "Error invalid argumanet";
    }
};
 BitStream() [1/4]
BitStream::~BitStream ()
Destructor.
Calls the function close().
Definition at line 24 of file BitStream.cpp.
                     {
    BitStream::close();
}
References close().
BitStream() [2/4]
BitStream::BitStream (string , char)
Bit buffer used for reading from a file.
Constructor.
Parameters
name The file path.
mode The mode in witch the BitStream operates 'r' to read, 'w' to write
 BitStream() [2/4]
BitStream::~BitStream ()
Destructor.
Calls the function close().
BitStream() [3/4]
BitStream::BitStream (string , char)
Constructor.
Parameters
name The file path.
mode The mode in witch the BitStream operates 'r' to read, 'w' to write
 BitStream() [3/4]
BitStream::~BitStream ()
Destructor.
Calls the function close().
BitStream() [4/4]
BitStream::BitStream (string , char)
Constructor.
Parameters
name The file path.
mode The mode in witch the BitStream operates 'r' to read, 'w' to write
 BitStream() [4/4]
BitStream::~BitStream ()
Destructor.
Calls the function close().
Member Function Documentation
close() [1/4]
void BitStream::close ()
Writes any remaining bits and closes the file stream.
close() [2/4]
void BitStream::close ()
Writes any remaining bits and closes the file stream.
close() [3/4]
void BitStream::close ()
Writes any remaining bits and closes the file stream.
Definition at line 18 of file BitStream.cpp.
                     {
    if(currentBit <= 8 && currentBit != 0)
        file.write(reinterpret_cast<char*>(&bitBuffer),1);
    file.close();
}
Referenced by main(), and ~BitStream().
close() [4/4]
void BitStream::close ()
Writes any remaining bits and closes the file stream.
hasNext() [1/4]
bool BitStream::hasNext ()
Checks if the file stream has bits left to read.
Returns
true if there are remaining bits, false if there are not.
hasNext() [2/4]
bool BitStream::hasNext ()
Checks if the file stream has bits left to read.
Returns
true if there are remaining bits, false if there are not.
hasNext() [3/4]
bool BitStream::hasNext ()
Checks if the file stream has bits left to read.
Returns
true if there are remaining bits, false if there are not.
Definition at line 28 of file BitStream.cpp.
                       {
    if (currentBit < 8)
        return true;
    if (file.peek() != EOF)
        return true;
    return false;
}
hasNext() [4/4]
bool BitStream::hasNext ()
Checks if the file stream has bits left to read.
Returns
true if there are remaining bits, false if there are not.
open() [1/2]
void BitStream::open (string)
Opens a file as a filestream.
Parameters
name The file path.
open() [2/2]
void BitStream::open (string)
Opens a file as a filestream.
Parameters
name The file path.
readBit() [1/4]
int BitStream::readBit ()
Reads a single bit from the file stream.
Returns
The bit read.
readBit() [2/4]
int BitStream::readBit ()
Reads a single bit from the file stream.
Returns
The bit read.
readBit() [3/4]
int BitStream::readBit ()
Reads a single bit from the file stream.
Returns
The bit read.
Definition at line 57 of file BitStream.cpp.
                      {
    char returnChar;
    if (currentBit >= 8 || currentBit == 0){
        currentBit = 0;
        file.read(&bitBuffer,sizeof(char));
    }
    returnChar = bitBuffer>>(7-currentBit) & 1;
    currentBit++;
    return returnChar;
}
readBit() [4/4]
int BitStream::readBit ()
Reads a single bit from the file stream.
Returns
The bit read.
readBits() [1/4]
int BitStream::readBits (int)
Reads an array of bits from the file stream.
Returns
The bit array read.
Parameters
n how many bits to be read.
readBits() [2/4]
int BitStream::readBits (int)
Reads an array of bits from the file stream.
Returns
The bit array read.
Parameters
n how many bits to be read.
readBits() [3/4]
int BitStream::readBits (int n)
Reads an array of bits from the file stream.
Returns
The bit array read.
Parameters
n how many bits to be read.
Definition at line 68 of file BitStream.cpp.
                            {
    int val = 0;
    int bit;
    for (size_t i = 0; i < n; i++)
    {
        bit = readBit();
        val |= bit<<n-1-i;
    }
    return val;
    
}
Referenced by main().
readBits() [4/4]
int BitStream::readBits (int)
Reads an array of bits from the file stream.
Returns
The bit array read.
Parameters
n how many bits to be read.
writeBit() [1/4]
void BitStream::writeBit (int)
Writes a single bit to the file stream.
Parameters
bit the bit to be written.
writeBit() [2/4]
void BitStream::writeBit (int)
Writes a single bit to the file stream.
Parameters
bit the bit to be written.
writeBit() [3/4]
void BitStream::writeBit (int bit)
Writes a single bit to the file stream.
Parameters
bit the bit to be written.
Definition at line 36 of file BitStream.cpp.
                               {
    if (bit)
        bitBuffer |= (1<<7-currentBit);
    currentBit++;
    if (currentBit == 8)
    {
        file.write(reinterpret_cast<char*>(&bitBuffer),1);
        currentBit = 0;
        bitBuffer = 0;
    }
}
writeBit() [4/4]
void BitStream::writeBit (int)
Writes a single bit to the file stream.
Parameters
bit the bit to be written.
writeBits() [1/4]
void BitStream::writeBits (int , int)
Writes an array of bits to the file stream.
Parameters
bit the array of bits to be written.
size the size of the bit array.
writeBits() [2/4]
void BitStream::writeBits (int , int)
Writes an array of bits to the file stream.
Parameters
bit the array of bits to be written.
size the size of the bit array.
writeBits() [3/4]
void BitStream::writeBits (int bits, int size)
Writes an array of bits to the file stream.
Parameters
bit the array of bits to be written.
size the size of the bit array.
Definition at line 50 of file BitStream.cpp.
                                          {
    for (size_t i = 0; i < size; i++){
        writeBit(bits & 1<<size-1-i);
    }
    
}
Referenced by main().
writeBits() [4/4]
void BitStream::writeBits (int , int)
Writes an array of bits to the file stream.
Parameters
bit the array of bits to be written.
size the size of the bit array.
Member Data Documentation
bitBuffer
char BitStream::bitBuffer = 0 [private]
Bit buffer used for writing in a file.
Definition at line 22 of file BitStream.h.
currentBit
unsigned int BitStream::currentBit = 0 [private]
Bit counter used when writing to a file.
Used to keep track of the current bit in the bit buffer.
Definition at line 27 of file BitStream.h.
file
fstream BitStream::file [private]
The file stream.
Definition at line 17 of file BitStream.h.
The documentation for this class was generated from the following files:
src/BitStream/include/BitStream.h
src/BitStream/src/BitStream.cpp