Player Class Reference
This class represents a video player/image displayer.
#include <Player.hpp>
Public Member Functions
Player (String media)
Constructor.
~Player ()
Destructor.
void display (function< Mat(Mat)>)
Displays the processed videos.
bool isOpen ()
Checks if video instance is open or not.
Static Public Member Functions
static Mat frameRgb2Yuv (Mat frame)
Converts a frame/image from the RGB scale to the YUV scale.
static Mat frameYuv2Rgb (Mat frame)
Converts a frame/image from the YUV scale to the RGB scale.
static void getColorHistograms (Mat frame)
Displays the three histograms (for Red, Green and Blue) from an image.
static Mat toGrayscale (Mat frame)
Converts a frame/image to grayscale.
static Mat threshold (Mat frame, double threshold)
Converts a frame/image to a black and white image based on a specified threshold.
static Mat addWatermark (Mat frame, Mat watermark, float alpha, int x, int y)
Adds a watermark to a frame/image.
static Mat grayHistEqualization (Mat frame)
Applies histogram equalization to a gray frame/image.
static Mat colorHistEqualization (Mat frame)
Applies histogram equalization to a colored frame/image.
static Mat gaussianBlur (Mat frame, int ksize, double sigma)
Applies gaussian blur to a gray frame/image.
static Mat boxFilter (Mat frame, Size ksize)
Applies blur to a gray frame/image using a box filter.
Static Private Member Functions
static void printHistogram (vector< int > hist, int color)
Displays a histogram. Only used internally by other functions.
static void getHistogram (Mat frame, int color)
Calculates a histogram. Only used internally by other functions.
static Mat histogramEqualization (Mat frame)
Applies histogram equalization. Only used internally by other functions.
Private Attributes
VideoCapture * cap
Video capture instance.
string name
Media file name.
Detailed Description
This class represents a video player/image displayer.
It's methods include the conversion between RGB and YUV and low level image processing operations. The decision to make all the processing methods static was made to allow one object to manipulate more than one media. Since the videos and images are never saved, it can be done and avoids the creation of a large number of objects.
Definition at line 20 of file Player.hpp.
Constructor & Destructor Documentation
Player()
Player::Player (String media)
Constructor.
Parameters
media A string representing the path to the media file.
Definition at line 12 of file Player.cpp.
                          {
    this->name = media;
    cap = new VideoCapture(media);
}
References cap, and name.
~Player()
Player::~Player ()
Destructor.
Definition at line 17 of file Player.cpp.
               {
    delete cap;
}
References cap.
Member Function Documentation
addWatermark()
Mat Player::addWatermark (Mat frame, Mat watermark, float alpha, int x, int y) [static]
Adds a watermark to a frame/image.
Parameters
frame The frame to which the watermark will be added.
watermark The image used as the watermark.
alpha The transparency of the watermark (value ranges from 0 to 1).
x X-axis value of the watermark position.
y Y-axis value of the watermark position.
Returns
The converted frame.
Definition at line 208 of file Player.cpp.
{
    for (int row = 0; row < watermark.rows; row++){
        for (int col = 0; col < watermark.cols; col++){
            if (row + x < frame.rows && col + y < frame.cols){
                frame.at<Vec3b>(row + x, col + y) *= 1 - alpha;
                frame.at<Vec3b>(row + x, col + y) += watermark.at<Vec3b>(row, col) * alpha;
            }
        }
    }
    return frame;
}
Referenced by main().
boxFilter()
Mat Player::boxFilter (Mat frame, Size ksize) [static]
Applies blur to a gray frame/image using a box filter.
Parameters
frame The frame to be converted.
Returns
The converted frame.
Definition at line 276 of file Player.cpp.
{
    Mat kernel = Mat::ones(ksize.height, ksize.width, CV_64F);
    kernel *= 1.0 / (ksize.width * ksize.height);
    Mat result;
    filter2D(frame, result, -1, kernel);
    return result;
}
Referenced by main().
colorHistEqualization()
Mat Player::colorHistEqualization (Mat frame) [static]
Applies histogram equalization to a colored frame/image.
Uses a auxiliar private function.
Parameters
frame The frame to be converted.
Returns
The converted frame.
Definition at line 194 of file Player.cpp.
{
    Mat ycrcb_img;
    cvtColor(frame,ycrcb_img, COLOR_BGR2YCrCb);
    vector<Mat> channels;
    split(ycrcb_img, channels);
    channels[0] = histogramEqualization(channels[0]);
    merge(channels, ycrcb_img);
    cvtColor(ycrcb_img, ycrcb_img, COLOR_YCrCb2BGR);
    return ycrcb_img;
}
References histogramEqualization().
Referenced by main().
display()
void Player::display (function< Mat(Mat)> filter = NULL)
Displays the processed videos.
Parameters
function A static function from the class player that corresponds to the filter choosen by the user. The function is called with the Mat created from the media passed in the constructor as its argument.
Definition at line 64 of file Player.cpp.
                                                  {
    string media = this->name;
    string ext = media.substr(media.find_last_of("."), media.size()-1);
    
    if (ext == ".jpg" || ext == ".png" || ext == ".jpeg"){
        Mat img = imread(media, 1);
        Mat newImg;
        if(filter != NULL){
            newImg = filter(img);
        }
        else{
            newImg = img;
        }
        if(newImg.rows > 0 && newImg.cols > 0){
            imshow("image", newImg);
            waitKey(0);
            destroyAllWindows();
        }
        return;
    }
    while(1){
        Mat frame,newframe;
        this->cap->read(frame);
        if(filter != NULL){
            frame = filter(frame);
        }
        else{
            newframe = frame;
        }
        imshow(this->name,frame);
        char c=(char)waitKey(25);
            if(c==27)
                break;
    }
    cap->release();
    destroyAllWindows();
}
References cap, and name.
Referenced by main().
frameRgb2Yuv()
Mat Player::frameRgb2Yuv (Mat frame) [static]
Converts a frame/image from the RGB scale to the YUV scale.
Parameters
frame The frame to be converted.
Returns
The converted frame.
Definition at line 25 of file Player.cpp.
                                 {
    for(int i = 0; i < frame.rows; i++){
        for(int j = 0; j < frame.cols; j++){
            uint r = frame.at<Vec3b>(i,j)[2];
            uint g = frame.at<Vec3b>(i,j)[1];
            uint b = frame.at<Vec3b>(i,j)[0];
            uint y = 0.299*r+0.587*g+0.114*b;
            uint cb = 128+0.564*((int)b-(int)y);
            uint cr = 128+0.713*((int)r-(int)y);
            frame.at<Vec3b>(i,j)[0] = y;
            frame.at<Vec3b>(i,j)[1] = cb;
            frame.at<Vec3b>(i,j)[2] = cr;
        }
    }
    return frame;
}
Referenced by main().
frameYuv2Rgb()
Mat Player::frameYuv2Rgb (Mat frame) [static]
Converts a frame/image from the YUV scale to the RGB scale.
Parameters
frame The frame to be converted.
Returns
The converted frame.
Definition at line 45 of file Player.cpp.
                                 {
    for(int i = 0; i < frame.rows; i++){
        for(int j = 0; j < frame.cols; j++){
            uint y = frame.at<Vec3b>(i,j)[0];
            uint cb = frame.at<Vec3b>(i,j)[1];
            uint cr = frame.at<Vec3b>(i,j)[2];
            uint r = y+1.13983*((int)cr-128);
            uint g = y-0.39465*((int)cb-128)-0.58060*((int)cr-128);
            uint b = y+2.03211*((int)cb-128);
            frame.at<Vec3b>(i,j)[2] = r;
            frame.at<Vec3b>(i,j)[1] = g;
            frame.at<Vec3b>(i,j)[0] = b;
        }
    }
        return frame;
}
Referenced by main().
gaussianBlur()
Mat Player::gaussianBlur (Mat frame, int ksize, double sigma) [static]
Applies gaussian blur to a gray frame/image.
Parameters
frame The frame to be converted.
Returns
The converted frame.
Definition at line 250 of file Player.cpp.
                                                          {
    if (ksize % 2 == 0)
    {
        ksize++;
    }
    int radius = ksize / 2;
    Mat kernel(ksize, ksize, CV_64F);
    double sum = 0.0;
    for (int x = -radius; x <= radius; x++) {
        for (int y = -radius; y <= radius; y++) {
            double value = exp(-(x * x + y * y) / (2 * sigma * sigma));
            kernel.at<double>(x + radius, y + radius) = value;
            sum += value;
        }
    }
    kernel /= sum;
    Mat result;
    filter2D(frame, result, -1, kernel);
    return result;
}
Referenced by main().
getColorHistograms()
void Player::getColorHistograms (Mat frame) [static]
Displays the three histograms (for Red, Green and Blue) from an image.
Uses private auxiliar functionns to calculate and display the histograms.
Parameters
frame The frame to be converted.
Returns
The converted frame.
Definition at line 118 of file Player.cpp.
                                        {
    for(int i = 0; i < 3; i++){
        getHistogram(frame, i);
    }
}
References getHistogram().
Referenced by main().
getHistogram()
void Player::getHistogram (Mat frame, int color) [static], [private]
Calculates a histogram. Only used internally by other functions.
Parameters
frame The image to calculate from.
color The channel to be considered and the color (R,G or B) of the drawing of the histogram.
Definition at line 104 of file Player.cpp.
                                             {
    vector<int> histogram(256,0);
    int intensity;
    for(int i = 0; i < frame.rows; i++){
        for(int j = 0; j < frame.cols; j++){
            intensity = frame.at<Vec3b>(i,j)[color]; // b = 0, g = 1, r = 2
            histogram[intensity]++;
        }
    }
    printHistogram(histogram, color);
}
References printHistogram().
Referenced by getColorHistograms().
grayHistEqualization()
Mat Player::grayHistEqualization (Mat frame) [static]
Applies histogram equalization to a gray frame/image.
Uses a auxiliar private function.
Parameters
frame The frame to be converted.
Returns
The converted frame.
Definition at line 186 of file Player.cpp.
{
    Mat grayscaleImage(frame.rows, frame.cols, CV_8UC1);
    grayscaleImage = toGrayscale(frame);
    Mat equalizedImage = histogramEqualization(grayscaleImage);
    return equalizedImage;
}
References histogramEqualization(), and toGrayscale().
Referenced by main().
histogramEqualization()
Mat Player::histogramEqualization (Mat frame) [static], [private]
Applies histogram equalization. Only used internally by other functions.
Parameters
frame The frame to be converted.
Returns
The converted frame.
Definition at line 161 of file Player.cpp.
{
    Mat histogram;
    float Range[] = {0, 256};
    const float* HistRange = {Range};
    int npixels = 256;
    calcHist(&frame, 1, 0, Mat(), histogram, 1, &npixels, &HistRange, true, false);
    Mat cumsum = histogram.clone();
    for (int i = 1; i < 256; ++i) {
        cumsum.at<float>(i) += cumsum.at<float>(i - 1);
    }
    cumsum /= cumsum.at<float>(npixels - 1);
    cumsum *= 255;
    Mat equalizedImage(frame.size(), frame.type());
    for (int i = 0; i < frame.rows; ++i) {
        for (int j = 0; j < frame.cols; ++j) {
            equalizedImage.at<uchar>(i, j) = saturate_cast<uchar>(cumsum.at<float>(frame.at<uchar>(i, j)));
        }
    }
    return equalizedImage;
}
Referenced by colorHistEqualization(), and grayHistEqualization().
isOpen()
bool Player::isOpen ()
Checks if video instance is open or not.
Returns
true if it's open, false if it's not.
Definition at line 21 of file Player.cpp.
                   {
    return cap->isOpened();
}
References cap.
Referenced by main().
printHistogram()
void Player::printHistogram (vector< int > hist, int color) [static], [private]
Displays a histogram. Only used internally by other functions.
Drawing implementation based on example code found on OpenCV documentation, at: https://docs.opencv.org/3.4/d8/dbc/tutorial_histogram_calculation.html
Parameters
hist The histogram to be displayed.
color The color (R,G or B) of the drawing of the histogram.
Definition at line 125 of file Player.cpp.
                                                      {
    Scalar colorScalar;
    switch (color){
        case 2:
            colorScalar = Scalar(0, 0, 255);
            break;
        case 1:
            colorScalar = Scalar(0, 255, 0);
            break;
        case 0:
            colorScalar = Scalar(255, 0, 0);
            break;
        default:
            colorScalar = Scalar(255, 255, 255);
            break;
    }
    int histSize = 256;
    int hist_w = 512, hist_h = 400;
    int bin_w = cvRound((double) hist_w/histSize);
    Mat histImage(hist_h, hist_w, CV_8UC3, Scalar(0,0,0));
    normalize(hist, hist, 0, histImage.rows, NORM_MINMAX, -1, Mat());
    for(int i=1; i < histSize; i++){
        line(histImage, Point(bin_w*(i-1), hist_h - cvRound(hist[i-1])),
        Point(bin_w*(i), hist_h - cvRound(hist[i])),
        colorScalar, 2, 8, 0);
    }
    imshow("Histogram", histImage);
    waitKey(0);
    destroyAllWindows();
}
Referenced by getHistogram().
threshold()
Mat Player::threshold (Mat frame, double threshold) [static]
Converts a frame/image to a black and white image based on a specified threshold.
Parameters
frame The frame to be converted.
threshold The value of the threshold.
Returns
The converted frame.
Definition at line 221 of file Player.cpp.
{
    frame = toGrayscale(frame);
    for (int row = 0; row < frame.rows; row++){
        for (int col = 0; col < frame.cols; col++){
            uchar pixel = frame.at<uchar>(row, col);
            if(pixel >= threshold){
                frame.at<uchar>(row, col) = 255;
            }
            else{
                frame.at<uchar>(row, col) = 0;
            }
        }
    }
    return frame;
}
References threshold(), and toGrayscale().
Referenced by main(), and threshold().
toGrayscale()
Mat Player::toGrayscale (Mat frame) [static]
Converts a frame/image to grayscale.
Parameters
frame The frame to be converted.
Returns
The converted frame.
Definition at line 238 of file Player.cpp.
{
    Mat result(frame.rows, frame.cols, CV_8UC1);
    for (int row = 0; row < frame.rows; row++){
        for (int col = 0; col < frame.cols; col++){
            Vec3b pixel = frame.at<Vec3b>(row, col);
            result.at<uchar>(row, col) = pixel[0] * 0.11 + pixel[1] * 0.59 + pixel[2] * 0.30;
        }
    }
    return result;
}
Referenced by grayHistEqualization(), main(), and threshold().
Member Data Documentation
cap
VideoCapture* Player::cap [private]
Video capture instance.
Used for when the media passed as argument is a video.
Definition at line 27 of file Player.hpp.
Referenced by display(), isOpen(), Player(), and ~Player().
name
string Player::name [private]
Media file name.
Used as media title and for reading the file when the media passed as argument is an image.
Definition at line 33 of file Player.hpp.
Referenced by display(), and Player().
The documentation for this class was generated from the following files:
src/videoPlayer/Player.hpp
src/videoPlayer/Player.cpp