Golomb Class Reference
A entropy encoder built with Golomb codes.
#include <Golomb.h>
Public Member Functions
Golomb (BitStream *bs, int n)
Constructor.
void encodeNumber (int)
Encodes number.
int decodeNumber ()
Decodes number.
void encodeMat (cv::Mat)
Encode an openCV map with golomb.
cv::Mat decodeMat (int cols, int rows)
Encode an openCV map with golomb.
Golomb (BitStream *bs, int n)
Constructor.
void encodeNumber (int)
Encodes number.
int decodeNumber ()
Decodes number.
void encodeMat (cv::Mat)
Encode an openCV Mat to a bitStream using Golomb.
cv::Mat decodeMat (int cols, int rows)
Decode a Golomb encoded bitStream to a Mat.
Private Attributes
int m
Parameter used to divide the number to be encoded.
int bits
Number of bits to be used in the formula.
BitStream * bitStream
Used to write bits encoded.
Detailed Description
A entropy encoder built with Golomb codes.
Definition at line 11 of file Golomb.h.
Constructor & Destructor Documentation
Golomb() [1/2]
Golomb::Golomb (BitStream * bs, int n)
Constructor.
Parameters
n Parameter used to divide the number to be encoded.
Definition at line 11 of file Golomb.cpp.
                                 {
    m = n;
    bitStream = bs;
    bits = floor(log2(m));
}
Golomb() [2/2]
Golomb::Golomb (BitStream * bs, int n)
Constructor.
Parameters
bs BitStream used to write the encoded bits.
n Parameter used to divide the number to be encoded.
Member Function Documentation
decodeMat() [1/2]
cv::Mat Golomb::decodeMat (int cols, int rows)
Encode an openCV map with golomb.
Parameters
image MawClass
Definition at line 65 of file Golomb.cpp.
                                        {
    cv::Mat image(rows,cols,CV_8UC1);
    for(int i = 0; i < rows; i++){
        for(int j = 0; j < cols; j++){
            uint p = decodeNumber();
            image.at<uchar>(i,j) = p;
        }
    }
    return image;
}
Referenced by decodeVideo(), and main().
decodeMat() [2/2]
cv::Mat Golomb::decodeMat (int cols, int rows)
Decode a Golomb encoded bitStream to a Mat.
Parameters
cols Number of columns of the Mat.
rows Number of rows of the Mat.
Returns
Decoded Mat.
decodeNumber() [1/2]
int Golomb::decodeNumber ()
Decodes number.
Returns
Decoded number.
decodeNumber() [2/2]
int Golomb::decodeNumber ()
Decodes number.
Parameters
numbers array of bits (ints) of number encoded.
Definition at line 35 of file Golomb.cpp.
                        {
    int quotient = 0;
    int n;
    int bit;
    while(bitStream->readBit() != 0){
        quotient++;
    }
    int reminder = bitStream->readBits(bits);
    if (reminder >= pow(2,bits+1)-m){
        reminder = reminder<<1;
        reminder |= bitStream->readBit();
        reminder = reminder - pow(2,bits+1)+m;
    }
    return quotient*m+reminder;
}
Referenced by decodeVideo(), and main().
encodeMat() [1/2]
void Golomb::encodeMat (cv::Mat)
Encode an openCV Mat to a bitStream using Golomb.
Parameters
image Image in Mat format.
encodeMat() [2/2]
void Golomb::encodeMat (cv::Mat image)
Encode an openCV map with golomb.
Parameters
image MawClass
Definition at line 55 of file Golomb.cpp.
                                 {
    for(int i = 0; i < image.rows; i++){
        for(int j = 0; j < image.cols; j++){
            uint p = image.at<uchar>(i,j);
            encodeNumber(p);
        }
    }
}
Referenced by encodeVideo(), and main().
encodeNumber() [1/2]
void Golomb::encodeNumber (int)
Encodes number.
Parameters
number Number to be encoded.
encodeNumber() [2/2]
void Golomb::encodeNumber (int number)
Encodes number.
Parameters
number Number to be encoded.
Returns
Number encoding.
Definition at line 17 of file Golomb.cpp.
                                   {
    int quotient = floor(number/m);
    int reminder = number % m;
    for (int i = 0; i < quotient; i++){
        bitStream->writeBit(1);
    }
    bitStream->writeBit(0);
    if (reminder < pow(2,bits+1)-m){
        bitStream->writeBits(reminder,bits);
    }else{
        reminder = reminder + pow(2,bits+1)-m;
        bitStream->writeBits(reminder,bits+1);
    }
}
Referenced by encodeVideo(), and main().
Member Data Documentation
bits
int Golomb::bits [private]
Number of bits to be used in the formula.
Definition at line 22 of file Golomb.h.
bitStream
BitStream * Golomb::bitStream [private]
Used to write bits encoded.
BitStream used to write the encoded bits.
Definition at line 26 of file Golomb.h.
m
int Golomb::m [private]
Parameter used to divide the number to be encoded.
Definition at line 17 of file Golomb.h.
The documentation for this class was generated from the following files:
src/GolombCoding/include/Golomb.h
src/GolombCoding/Golomb.cpp