src/hibrid-encoder/include/intraEncoder.h File Reference
#include `opencv2/opencv.hpp`
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/plot.hpp>
#include <iostream>
Functions
int jpeg_ls_predictor (int a, int b, int c)
JPEG-LS non-linear predictor.
Mat getResidualsJPEG_LS (Mat image)
Get residuals from an image using JPEG-LS non-linear predictor.
Mat getOriginalJPEG_LS (Mat residuals)
Get original image from residuals using JPEG-LS non-linear predictor.
void encodeVideo (string outputFile, string file)
Encode a video using JPEG-LS non-linear predictor.
void decodeVideo (string outputFile, string file)
Decode a video using JPEG-LS non-linear predictor.
Function Documentation
decodeVideo()
void decodeVideo (string outputFile, string file)
Decode a video using JPEG-LS non-linear predictor.
Parameters
outputFile Output file name.
file Input file name.
Definition at line 95 of file intraEncoder.cpp.
                                               {
    BitStream bs(file,'r');
    string format = ".mp4";
    Mat frame;
    // char c;
    // c = bs.readBits(8);
    // while(c !='\n'){
    // format += c;
    // c = bs.readBits(8);
    // }
    Golomb gl(&bs,50);
    int fourcc = VideoWriter::fourcc('m','p','4','v');
    int framesCount = gl.decodeNumber();
    int cols = gl.decodeNumber();
    int row = gl.decodeNumber();
    int fps = gl.decodeNumber();
    Size size(cols,row);
    VideoWriter out(outputFile+format,fourcc,fps,size,false);
    for(int i = 0; i<framesCount; i++){
        frame = gl.decodeMat(cols,row);
        frame = getOriginalJPEG_LS(frame);
        //cvtColor(frame,frame,COLOR_GRAY2BGR);
        out << frame;
    }
    out.release();
}
Referenced by main().
encodeVideo()
void encodeVideo (string outputFile, string file)
Encode a video using JPEG-LS non-linear predictor.
Parameters
outputFile Output file name.
file Input file name.
Definition at line 67 of file intraEncoder.cpp.
                                               {
    // string format = file.substr(file.find_last_of(".") + 1);
    // format+= '\n';
    VideoCapture cap(file);
    BitStream ouFile(outputFile,'w');
    // for(int i = 0; i < format.length(); i++){
    // char c = format.at(i);
    // ouFile.writeBits(c,8);
    // }
    Mat frame;
    cap.read(frame);
    Golomb encoder(&ouFile,50);
    encoder.encodeNumber(cap.get(CAP_PROP_FRAME_COUNT));
    encoder.encodeNumber(frame.cols);
    encoder.encodeNumber(frame.rows);
    encoder.encodeNumber(cap.get(CAP_PROP_FPS));
    while(1){
        if (frame.empty())
            break;
        cvtColor(frame,frame,COLOR_BGR2GRAY);
        frame = getResidualsJPEG_LS(frame);
        encoder.encodeMat(frame);
        cap >> frame;
    }
    cap.release();
}
Referenced by main().
getOriginalJPEG_LS()
Mat getOriginalJPEG_LS (Mat residuals)
Get original image from residuals using JPEG-LS non-linear predictor.
Parameters
residuals Residuals to get original image from.
Returns
Original image on Mat format.
Definition at line 46 of file intraEncoder.cpp.
                                     {
    
    Mat original = residuals.clone();
    for (int row = 0; row < original.rows; row++){
        for (int col = 0; col < original.cols; col++){
            
            int estimate = 0;
            if(row > 0 && col > 0){
                int a = original.at<uchar>(row,col-1);
                int b = original.at<uchar>(row-1,col);
                int c = original.at<uchar>(row-1,col-1);
                estimate = jpeg_ls_predictor(a,b,c);
            }
            original.at<uchar>(row,col) = original.at<uchar>(row,col) + estimate;
        }
    }
    return original;
}
Referenced by DecodeHybrid().
getResidualsJPEG_LS()
Mat getResidualsJPEG_LS (Mat image)
Get residuals from an image using JPEG-LS non-linear predictor.
Parameters
image Image to get residuals from.
Returns
Residuals on Mat format.
Definition at line 26 of file intraEncoder.cpp.
                                  {
    Mat residuals(image.rows, image.cols, CV_8UC1);
    for (int row = 0; row < image.rows; row++){
        for (int col = 0; col < image.cols; col++){
            
            int estimate = 0;
            if(row > 0 && col > 0){
                int a = image.at<uchar>(row,col-1);
                int b = image.at<uchar>(row-1,col);
                int c = image.at<uchar>(row-1,col-1);
                estimate = jpeg_ls_predictor(a,b,c);
            }
            residuals.at<uchar>(row,col) = image.at<uchar>(row,col) - estimate;
        }
    }
    return residuals;
}
Referenced by EncodeHybrid().
jpeg_ls_predictor()
int jpeg_ls_predictor (int a, int b, int c)
JPEG-LS non-linear predictor.
Parameters
a Left pixel.
b Upper pixel.
c Upper left pixel.
Returns
Pixel prediction.
Definition at line 14 of file intraEncoder.cpp.
                                          {
    if (c >= max(a,b)){
        return min(a, b);
    }
    else if(c <= min(a,b)){
        return max(a, b);
    }
    else{
        return a + b - c;
    }
}