src/videoPlayer/Player.cpp File Reference
#include `opencv2/opencv.hpp`
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/plot.hpp>
#include <iostream>
#include <numeric>
#include `Player.hpp`
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 285 of file Player.cpp.
                                {
    // Check if at least one argument is provided
    if (argc < 2) {
        std::cerr << "Usage: " << argv[0] << " <video/image> [option]" << std::endl;
        return 1;
    }
    Player p1(argv[1]);
    if(!p1.isOpen()){
        cout << "Could not open media.\n";
        return -1;
    }
    if (argc < 3) {
        p1.display();
    }
    string filter = argv[2];
    if (filter == "histogram"){
        Mat img = imread(argv[1]);
        p1.getColorHistograms(img);
    }
    else if (filter == "grayscale"){
        p1.display(Player::toGrayscale);
    }
    else if (filter == "rgb2yuv"){
        p1.display(Player::frameRgb2Yuv);
    }
    else if (filter == "yuv2rgb"){
        p1.display(Player::frameYuv2Rgb);
    }
    else if (filter == "colorhisteq"){
        p1.display(Player::colorHistEqualization);
    }
    else if (filter == "grayhisteq"){
        p1.display(Player::grayHistEqualization);
    }
    else if (filter == "threshold"){
        double threshold = 127;
        if (argc >= 4) {
            threshold = stoi(argv[3]);
        }
        auto threshold_filter = [threshold](Mat frame){
            return Player::threshold(frame, threshold);
        };
        p1.display(threshold_filter);
    }
    else if (filter == "gaussian"){
        int ksize = 5;
        double sigma = 2;
        
        if (argc >= 4) {
            ksize = stoi(argv[3]);
        }
        if (argc >= 5) {
            sigma = stod(argv[3]);
        }
        auto gaussian_filter = [ksize, sigma](Mat frame){
            return Player::gaussianBlur(frame, ksize, sigma);
        };
        p1.display(gaussian_filter);
    }
    else if (filter == "blur"){
        int ksize = 5;
        if (argc >= 4) {
            ksize = stoi(argv[3]);
        }
        auto blur_filter = [ksize](Mat frame){
            return Player::boxFilter(frame, Size(ksize,ksize));
        };
        p1.display(blur_filter);
    }
    else if (filter == "watermark"){
        float alpha = 1;
        int x = 0;
        int y = 0;
        
        if (argc < 4) {
            cerr << "Usage for watermark: " << argv[0] << " <video> watermark <watermark>" << endl;
            return -1;
        }
        Mat watermark = imread(argv[3]);
        if (argc >= 5) {
            x = stoi(argv[4]);
        }
        if (argc >= 6) {
            y = stoi(argv[5]);
        }
        if (argc >= 7) {
            alpha = stod(argv[6]);
        }
        auto watermark_filter = [x, y, alpha, watermark](Mat frame){
            return Player::addWatermark(frame, watermark, alpha, x, y);
        };
        p1.display(watermark_filter);
    }
    else{
        std::cerr << "invalid filter" << endl;
        return -1;
    }
     
    return 0;
}
References Player::addWatermark(), Player::boxFilter(), Player::colorHistEqualization(), Player::display(), Player::frameRgb2Yuv(), Player::frameYuv2Rgb(), Player::gaussianBlur(), Player::getColorHistograms(), Player::grayHistEqualization(), Player::isOpen(), Player::threshold(), and Player::toGrayscale().