ArgParser Class Reference
A class to parse command line arguments.
#include <ArgParser.h>
Public Member Functions
ArgParser (std::vector< std::string >)
Constructor.
int hasOpetion (std::string)
Checks if the vector of arguments has a given option.
std::string getValue (int)
Gets the value of an option.
std::string getValueNoOption ()
Gets the first value that is not an option.
Private Attributes
std::vector< std::string > args
The vector of arguments.
Detailed Description
A class to parse command line arguments.
Definition at line 9 of file ArgParser.h.
Constructor & Destructor Documentation
ArgParser()
ArgParser::ArgParser (std::vector< std::string > args)
Constructor.
Parameters
args The vector of arguments.
Definition at line 7 of file ArgParser.cpp.
                                             {
    this->args = args;
}
References args.
Member Function Documentation
getValue()
std::string ArgParser::getValue (int i)
Gets the value of an option.
Parameters
i The index of the option.
Returns
The value of the option.
Definition at line 21 of file ArgParser.cpp.
                                   {
    return args[i+1];
}
References args.
Referenced by main().
getValueNoOption()
std::string ArgParser::getValueNoOption ()
Gets the first value that is not an option.
Returns
The value.
Definition at line 25 of file ArgParser.cpp.
                                     {
    if (args.size() == 0){
        return "";
    }
    if(args[0].at(0) != '-'){
        return args[0];
    }
    for(int i = 1; i < args.size(); i++){
        if(args[i-1].at(0) != '-'){
            return args[i];
        }
    }
    return "";
}
References args.
Referenced by main().
hasOpetion()
int ArgParser::hasOpetion (std::string str)
Checks if the vector of arguments has a given option.
Parameters
str The option to be checked.
Returns
The index of the option if it exists, -1 if it does not.
Definition at line 12 of file ArgParser.cpp.
                                      {
    for(int i = 0; i < args.size(); i++){
        if(args[i].compare(str) == 0){
            return i;
        }
    }
    return -1;
}
References args.
Referenced by main().
Member Data Documentation
args
std::vector<std::string> ArgParser::args [private]
The vector of arguments.
Definition at line 15 of file ArgParser.h.
Referenced by ArgParser(), getValue(), getValueNoOption(), and hasOpetion().
The documentation for this class was generated from the following files:
include/ArgParser.h
src/ArgParser.cpp