include/hibridEncoder.h File Reference
#include `Golomb.h`
#include `intraEncoder.h`
#include <vector>
Classes
class Block
A class to represent a fixed-size block of pixels from a frame.
struct YUVFrame
A structuer to represent a frame.
struct VideoInfo
A structure to represent the video information.
Functions
bool parseYUV4MPEG2 (string filename, VideoInfo &info)
A parser for videos in YUV4MPEG2 format.
Block FindBestBlock (Block block, const vector< vector< char >> &previous, const vector< vector< char >> &current, int searchArea) void EncodeInterFrame(YUVFrame &currentFrame
Search algoritthm to find best block within the defined search area.
Mat DecodeInterFrame (Mat previousFrame, int blockSize, Golomb *gl)
Inter frame encoder.
void EncodeIntraFrame (YUVFrame frame, int blockSize, Golomb *gl)
Intra frame encoder.
YUVFrame DecodeIntraFrame (int rows, int cols, Golomb *gl)
Intra frame decoder.
void WriteYUVFrameToFile (string fileName, YUVFrame &frame)
Writes a YUV frame to a file.
void EncodeHybrid (string outputfile, string inputFile, int periodicity, int blockSize, int SearchArea, int quantizationY, int quantizationU, int quantizationV, int golomb)
Hybrid (inter + intra) encoder.
void DecodeHybrid (string outputFile, string inputFile, int golomb)
Hybrid (inter + intra) frame decoder.
Variables
Block YUVFrame & previousFrame
Block YUVFrame int blockSize
Block YUVFrame int int searchArea
Block YUVFrame int int Golomb * gl
Block YUVFrame int int Golomb int quantizationY
Block YUVFrame int int Golomb int int quantizationU
Block YUVFrame int int Golomb int int int quantizationV
Function Documentation
DecodeHybrid()
void DecodeHybrid (string outputFile, string inputFile, int golomb)
Hybrid (inter + intra) frame decoder.
Parameters
outputFile The name of the output file.
inputFile The name of the input file.
golomb The golomb value.
Definition at line 376 of file hibridEncoder.cpp.
{
    BitStream bs(inputFile, 'r');
    Golomb gl(&bs, golomb);
    int frameCount = gl.decodeNumber();
    int rows = gl.decodeNumber();
    int cols = gl.decodeNumber();
    int blockSize = gl.decodeNumber();
    
    ofstream fileStream(outputFile);
    if (fileStream.is_open()) {
        fileStream << gl.decodeString() << endl;
        fileStream.close();
    } else {
        cerr << "Unable to open the file." << endl;
        return;
    }
    YUVFrame previousFrame, frame;
    for (int i = 0; i < frameCount; i++)
    {
        cout << "decoding frame " << i+1 << "/" << frameCount << endl;
        int isIntraEncoded = bs.readBit();
        if (isIntraEncoded == 1)
        {
            frame = DecodeIntraFrame(rows, cols, &gl);
        }
        else
        {
            frame = DecodeInterFrame(previousFrame, blockSize, &gl);
        }
        WriteYUVFrameToFile(outputFile, frame);
        previousFrame = frame;
    }
}
References blockSize, DecodeInterFrame(), DecodeIntraFrame(), gl, previousFrame, BitStream::readBit(), and WriteYUVFrameToFile().
Referenced by main().
DecodeInterFrame()
Mat DecodeInterFrame (Mat previousFrame, int blockSize, Golomb * gl)
Inter frame encoder.
Parameters
previousFrame The previous frame.
residuals The calculated residuals.
countMotionVectors The value of the actual count of the motion vectors.
blockSize The size of each block.
gl The Golomb object used to encode the motion vectors.
DecodeIntraFrame()
YUVFrame DecodeIntraFrame (int rows, int cols, Golomb * gl)
Intra frame decoder.
Parameters
rows The number of rows of the frame.
cols The number of columns of the frame.
gl The Golomb object used to decode the residuals.
Returns
The decoded frame.
Definition at line 290 of file hibridEncoder.cpp.
                                                         {
    
    YUVFrame original;
    original.rows = rows;
    original.cols = cols;
    for (int plane = 0; plane <= 2; plane++){
        vector<vector<char>> residualsPlane(rows, vector<char>(cols));
        vector<vector<char>> originalPlane(rows, vector<char>(cols));
        for (int row = 0; row < rows; row++){
            for (int col = 0; col < cols; col++){
                
                int estimate = 0;
                residualsPlane[row][col] = gl->decodeNumber();
                if(row > 0 && col > 0){
                    int a = originalPlane[row][col-1];
                    int b = originalPlane[row-1][col];
                    int c = originalPlane[row-1][col-1];
                    estimate = jpeg_ls_predictor(a,b,c);
                }
                // original = residuals + estimate
                originalPlane[row][col] = residualsPlane[row][col] + estimate;
            }
        }
        switch(plane) {
            case 0:
                original.Y = originalPlane;
                break;
            case 1:
                original.U = originalPlane;
                break;
            case 2:
                original.V = originalPlane;
                break;
        }
    }
    return original;
}
References YUVFrame::cols, gl, jpeg_ls_predictor(), YUVFrame::rows, YUVFrame::U, YUVFrame::V, and YUVFrame::Y.
Referenced by DecodeHybrid().
EncodeHybrid()
void EncodeHybrid (string outputfile, string inputFile, int periodicity, int blockSize, int SearchArea, int quantizationY, int quantizationU, int quantizationV, int golomb)
Hybrid (inter + intra) encoder.
Parameters
outputfile The name of the output file.
inputFile The name of the input file.
periodicity The periodicity of the key frames.
blockSize The size of each block.
searchArea The size of the search area.
quantizationY The quantization value for the Y plane.
quantizationU The quantization value for the U plane.
quantizationV The quantization value for the V plane.
golomb The golomb value.
Definition at line 341 of file hibridEncoder.cpp.
{
    VideoInfo video_info;
    parseYUV4MPEG2(inputFile, video_info);
    
    BitStream bs(outputfile, 'w');
    Golomb gl(&bs, golomb);
    gl.encodeNumber(video_info.frames.size()); // number of frames
    gl.encodeNumber(video_info.rows); // frame rows
    gl.encodeNumber(video_info.cols); // frame columns
    gl.encodeNumber(blockSize); // block size
    gl.encodeString(video_info.header);
    int counter = 0;
    YUVFrame previousFrame, frame;
    for(int i = 0; i < video_info.frames.size(); i++){
        //cout << "encoding frame " << i+1 << "/" << video_info.frames.size() << endl;
        frame = video_info.frames[i];
        if (counter == periodicity || i == 0){
            bs.writeBit(1);
            EncodeIntraFrame(frame, blockSize, &gl);
            counter = 0;
        }
        else {
            bs.writeBit(0);
            EncodeInterFrame(frame, previousFrame, blockSize, SearchArea, &gl, quantizationY, quantizationU, quantizationV);
            counter += 1;
        }
        previousFrame = frame;
    }
}
References blockSize, VideoInfo::cols, EncodeInterFrame(), EncodeIntraFrame(), VideoInfo::frames, gl, VideoInfo::header, parseYUV4MPEG2(), previousFrame, quantizationU, quantizationV, quantizationY, VideoInfo::rows, and BitStream::writeBit().
Referenced by main(), and TestGolomb().
EncodeIntraFrame()
void EncodeIntraFrame (YUVFrame frame, int blockSize, Golomb * gl)
Intra frame encoder.
Parameters
frame The frame to be encoded.
blockSize The size of each block.
gl The Golomb object used to encode the residuals.
Definition at line 268 of file hibridEncoder.cpp.
                                                                {
    for (int plane = 0; plane <= 2; plane++)
    {
        for (int row = 0; row < frame.rows; row++)
        {
            for (int col = 0; col < frame.cols; col++)
            {
                int estimate = 0;
                if(row > 0 && col > 0){
                    int a = frame.getPlane(plane)[row][col-1];
                    int b = frame.getPlane(plane)[row-1][col];
                    int c = frame.getPlane(plane)[row-1][col-1];
                    estimate = jpeg_ls_predictor(a,b,c);
                }
                // residuals = original - estimate
                gl->encodeNumber(frame.getPlane(plane)[row][col] - estimate);
            }
        }
    }
}
References YUVFrame::cols, YUVFrame::getPlane(), gl, jpeg_ls_predictor(), and YUVFrame::rows.
Referenced by EncodeHybrid().
FindBestBlock()
Block FindBestBlock (Block block, const vector< vector< char >> & previous, const vector< vector< char >> & current, int searchArea) &
Search algoritthm to find best block within the defined search area.
Parameters
block The block to be compared to.
previous The previous frame.
current The current frame.
searchArea The size of the search area.
Inter frame decoder.
Parameters
currentFrame The current frame.
previousFrame The previous frame.
blockSize The size of each block.
searchArea The size of the search area.
gl The Golomb object used to decode the motion vectors.
quantizationY The quantization value for the Y plane.
quantizationU The quantization value for the U plane.
quantizationV The quantization value for the V plane.
parseYUV4MPEG2()
bool parseYUV4MPEG2 (string filename, VideoInfo & info)
A parser for videos in YUV4MPEG2 format.
Parameters
filename The name of the file to be parsed.
info The object where the video information will be stored.
Returns
true if the file was parsed successfully, false otherwise.
Definition at line 41 of file hibridEncoder.cpp.
                                                      {
    ifstream file(filename, ios::binary);
    if (!file.is_open()) {
        cerr << "Error opening file: " << filename << endl;
        return false;
    }
    string headerLine;
    getline(file >> ws, info.header);
    file.seekg(0);
    string format;
    file >> format;
    if(format != "YUV4MPEG2"){
        cerr << "Invalid video format";
        return false;
    }
    string current = "";
    while(true){
        file >> current;
        if(current == "FRAME"){
            break;
        }
        char first = current[0];
        switch(first) {
            case 'W':
                current.erase(0,1);
                info.cols = stoi(current);
                break;
            case 'H':
                current.erase(0,1);
                info.rows = stoi(current);
                break;
            case 'F':
                info.frame_rate = current;
                break;
            case 'I':
                info.interlacing = current;
                break;
            case 'A':
                info.aspect_ratio = current;
                break;
            case 'C':
                info.color_space = current;
                break;
        }
    }
    if(info.color_space.find("444") == string::npos){
        cerr << "This program currently only supports videos with 4:4:4 color space";
        return false;
    }
    
    vector<YUVFrame> frames;
    while(true){
        file.get(); // remove newline
        vector<vector<char>> y_plane(info.rows, vector<char>(info.cols));
        vector<vector<char>> u_plane(info.rows, vector<char>(info.cols));
        vector<vector<char>> v_plane(info.rows, vector<char>(info.cols));
        for (int i = 0; i < info.rows; ++i) {
            file.read(y_plane[i].data(), info.cols);
        }
        for (int i = 0; i < info.rows; ++i) {
            file.read(u_plane[i].data(), info.cols);
        }
        for (int i = 0; i < info.rows; ++i) {
            file.read(v_plane[i].data(), info.cols);
        }
        YUVFrame frame;
        frame.Y = y_plane;
        frame.U = u_plane;
        frame.V = v_plane;
        frame.rows = info.rows;
        frame.cols = info.cols;
        frames.push_back(frame);
        
        // get rid of "FRAME"
        string text;
        file >> text;
        
        if(file.eof()){
            break;
        }
    }
    file.close();
    info.frames = frames;
    return true;
}
References VideoInfo::aspect_ratio, VideoInfo::color_space, YUVFrame::cols, VideoInfo::cols, VideoInfo::frame_rate, VideoInfo::frames, VideoInfo::header, VideoInfo::interlacing, YUVFrame::rows, VideoInfo::rows, YUVFrame::U, YUVFrame::V, and YUVFrame::Y.
Referenced by EncodeHybrid().
WriteYUVFrameToFile()
void WriteYUVFrameToFile (string fileName, YUVFrame & frame)
Writes a YUV frame to a file.
Parameters
fileName The name of the file.
frame The frame to be written.
Definition at line 329 of file hibridEncoder.cpp.
                                                          {
    ofstream outputFile(fileName, ios::binary | ios::app);
    outputFile << "FRAME" << endl;
    for (int plane = 0; plane <= 2; plane++)
    {
        for (const auto& row : frame.getPlane(plane)) {
            outputFile.write(row.data(), row.size());
        }
    }
    return;
}
References YUVFrame::getPlane().
Referenced by DecodeHybrid().
Variable Documentation
blockSize
Block YUVFrame int blockSize
Definition at line 191 of file hibridEncoder.h.
Referenced by DecodeHybrid(), DecodeInterFrame(), EncodeHybrid(), EncodeInterFrame(), main(), and TestGolomb().
gl
Block YUVFrame int int Golomb* gl
Definition at line 191 of file hibridEncoder.h.
Referenced by DecodeHybrid(), DecodeInterFrame(), DecodeIntraFrame(), EncodeHybrid(), EncodeInterFrame(), and EncodeIntraFrame().
previousFrame
Block YUVFrame& previousFrame
Definition at line 191 of file hibridEncoder.h.
Referenced by DecodeHybrid(), DecodeInterFrame(), EncodeHybrid(), and EncodeInterFrame().
quantizationU
Block YUVFrame int int Golomb int int quantizationU
Definition at line 191 of file hibridEncoder.h.
Referenced by EncodeHybrid(), and EncodeInterFrame().
quantizationV
Block YUVFrame int int Golomb int int int quantizationV
Definition at line 191 of file hibridEncoder.h.
Referenced by EncodeHybrid(), and EncodeInterFrame().
quantizationY
Block YUVFrame int int Golomb int quantizationY
Definition at line 191 of file hibridEncoder.h.
Referenced by EncodeHybrid(), and EncodeInterFrame().
searchArea
Block YUVFrame int int searchArea
Definition at line 191 of file hibridEncoder.h.
Referenced by EncodeInterFrame(), FindBestBlock(), main(), and TestGolomb().